services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    networks:
      - nexus-network
    depends_on:
      - db
      - meilisearch

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile.prod
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - nexus-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - nexus_db_data:/var/lib/mysql
    networks:
      - nexus-network

  meilisearch:
    image: getmeili/meilisearch:latest
    restart: always
    environment:
      MEILI_MASTER_KEY: ${MEILISEARCH_KEY}
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - nexus_meilisearch_data:/meili_data
    networks:
      - nexus-network

networks:
  nexus-network:
    driver: bridge

volumes:
  nexus_db_data:
  nexus_meilisearch_data:
